# This file was entirely generated by AI. This is exempt from the GNU GPL V3 license and I claim no rights on it.

import serial
import os
import random
import pygame
import time

# --- Serial setup ---
ser = serial.Serial('/dev/cu.usbserial-0001', 9600, timeout=1)

# --- WAV files setup ---
folder1 = "1"
folder2 = "2"

wav_files1 = [f for f in os.listdir(folder1) if f.lower().endswith(".wav")]
wav_files2 = [f for f in os.listdir(folder2) if f.lower().endswith(".wav")]

if not wav_files1:
    print("No WAV files found in folder '1'.")
    exit(1)

if not wav_files2:
    print("No WAV files found in folder '2'.")
    exit(1)

headturn_file = "headturn.wav"
if not os.path.isfile(headturn_file):
    print(f"{headturn_file} not found in main directory.")
    exit(1)

# --- Initialize pygame mixer once ---
pygame.mixer.init()

print("Listening on serial port...")

try:
    while True:
        if ser.in_waiting:
            line = ser.readline().decode('utf-8', errors='ignore').strip()
            print(f"Received: {line}")

            # Determine which sound to play
            if line == "20DF28D7":
                wav_file = random.choice(wav_files1)
                file_path = os.path.join(folder1, wav_file)
                print(f"Playing random file from folder 1: {file_path}")

            elif line == "20DF9867":
                file_path = headturn_file
                print(f"Playing headturn file: {file_path}")

            elif line == "20DF18E7":
                wav_file = random.choice(wav_files2)
                file_path = os.path.join(folder2, wav_file)
                print(f"Playing random file from folder 2: {file_path}")

            else:
                continue  # ignore unknown codes

            # Play the selected WAV file (blocking)
            try:
                sound = pygame.mixer.Sound(file_path)
                channel = sound.play()
                while channel.get_busy():
                    pygame.time.wait(100)  # wait 100ms while sound plays
            except Exception as e:
                print(f"Error playing WAV file: {e}")
                continue

            # Send '1' over serial after playback
            ser.write(b'1\n')
            print("Sent '1' over serial")

        time.sleep(0.01)  # avoid busy-waiting

except KeyboardInterrupt:
    print("Exiting...")
finally:
    pygame.mixer.quit()
    ser.close()
